---
- hosts: all
  remote_user: root
  tasks:
    - name: Make sure we have all required packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - wget
        - git
        - make
        - gcc
        - tar
        - libseccomp-devel
        - golang
        - glib2-devel
        - glibc-static
        - container-selinux
        - btrfs-progs-devel
        - device-mapper-devel
        - glibc-devel
        - gpgme-devel
        - libassuan-devel
        - libgpg-error-devel
        - pkgconfig
        - json-glib-devel
        - skopeo-containers
        - docker
    - name: Make directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
           - /usr/local/go
           - /etc/systemd/system/kubelet.service.d/
           - /var/lib/etcd
           - /etc/cni/net.d
    - name: install Golang upstream in CentOS
      shell: |
              curl -fsSL "https://golang.org/dl/go1.8.3.linux-amd64.tar.gz" \
              | tar -xzC /usr/local
    - name: Set custom Golang path for CentOS
      lineinfile:
        dest: /root/.bashrc
        line: 'export PATH=/usr/local/go/bin:$PATH'
        insertafter: 'EOF'
        regexp: 'export PATH=\/usr\/local\/go\/bin:\$PATH'
        state: present
    - name: update all
      yum: name=* state=latest
    - name: clone runc
      git:
        repo: https://github.com/opencontainers/runc
        dest: /root/src/github.com/opencontainers/runc
      register: clone_runc
    - name: clone CRI-O
      git:
        repo: https://github.com/kubernetes-incubator/cri-o
        dest: /root/src/github.com/kubernetes-incubator/cri-o
        version: kube-1.6.x
      register: clone_crio
    - name: clone CNI
      git:
        repo: https://github.com/containernetworking/plugins
        dest: /root/src/github.com/containernetworking/plugins
      register: clone_cni
    - name: build runc
      shell: |
              cd /root/src/github.com/opencontainers/runc && \
              export GOPATH=/root && \
              make BUILDTAGS="seccomp selinux" && \
              make install
      when: clone_runc.changed
    - name: link runc
      file: src=/usr/local/sbin/runc dest=/usr/bin/runc state=link
    - name: build cri-o
      shell: |
              cd /root/src/github.com/kubernetes-incubator/cri-o && \
              make install.tools && \
              make && \
              make install && \
              make install.systemd && \
              make install.config
      when: clone_crio.changed
    - name: build CNI stuff
      shell: |
              cd /root/src/github.com/containernetworking/plugins && \
              ./build.sh && \
              mkdir -p /opt/cni/bin && \
              cp bin/* /opt/cni/bin/
      when: clone_cni.changed
    - name: run CRI-O with systemd cgroup manager
      replace:
        regexp: 'cgroupfs'
        replace: 'systemd'
        name: /etc/crio/crio.conf
        backup: yes
    - name: run with overlay2
      replace:
        regexp: 'storage_driver = ""'
        replace: 'storage_driver = "overlay2"'
        name: /etc/crio/crio.conf
        backup: yes
    - name: add overlay2 storage opts on RHEL/CentOS
      lineinfile:
        dest: /etc/crio/crio.conf
        line: '"overlay2.override_kernel_check=1"'
        insertafter: 'storage_option = \['
        regexp: 'overlay2\.override_kernel_check=1'
        state: present
    - name: enable and start CRI-O
      systemd:
        name: crio
        state: started
        enabled: yes
        daemon_reload: yes
    - name: modprobe br_netfilter
      command: "modprobe br_netfilter"
      ignore_errors: true
    - name: tune sysctl
      lineinfile:
        line: "net/bridge/bridge-nf-call-iptables = 1"
        dest: /etc/sysctl.conf
        insertafter: 'EOF'
        regexp: '\/net\/bridge\/bridge-nf-call-iptables = 1'
        state: present
      ignore_errors: true
    - name: reload sysctl
      command: "sysctl -p"
      ignore_errors: true
    - name: systemd dropin for kubeadm
      shell: |
              sh -c 'echo "[Service]
              Environment=\"KUBELET_EXTRA_ARGS=--enable-cri=true --container-runtime=remote --runtime-request-timeout=15m --image-service-endpoint /var/run/crio.sock --container-runtime-endpoint /var/run/crio.sock\"" > /etc/systemd/system/kubelet.service.d/0-crio.conf'
    - name: flush iptables
      command: "iptables -F"
    - name: Permanently disable selinux
      lineinfile:
        dest: /etc/selinux/config
        line: 'SELINUX=permissive'
        regexp: '^SELINUX='
